import json
import os
import sys
import base64

from aqt import mw
from aqt.utils import showInfo, showText
from aqt.qt import *

from .consts import addon_path
from . import config

from . import markdown
from .markdown.extensions.abbr import AbbrExtension
from .markdown.extensions.codehilite import CodeHiliteExtension
from .markdown.extensions.def_list import DefListExtension
from .markdown.extensions.fenced_code import FencedCodeExtension
from .markdown.extensions.footnotes import FootnoteExtension

from bs4 import BeautifulSoup, NavigableString, Tag


def generateHtmlFromMarkdown(field_plain, field_html):
    """Convert markdown text to HTML with syntax highlighting.
    
    Stores the original HTML in a data-attribute so it can be recovered later.
    """
    if not field_plain:
        field_plain = ""
    else:
        field_plain = field_plain.replace("\xc2\xa0", " ").replace("\xa0", " ")  # non-breaking space

    generated_html = markdown.markdown(field_plain, extensions=[
        AbbrExtension(),
        CodeHiliteExtension(
            noclasses=True,
            linenums=config.shouldShowCodeLineNums(),
            pygments_style=config.getCodeColorScheme()
        ),
        DefListExtension(),
        FencedCodeExtension(),
        FootnoteExtension(),
    ], output_format="html5")

    html_tree = BeautifulSoup(generated_html, 'html.parser')
    first_tag = findFirstTag(html_tree)

    # No HTML tags in output
    if not first_tag:
        # if not md_text, add space to prevent input field from shrinking in UI
        html_tree = BeautifulSoup(
            "<div>" + ("&nbsp;" if not generated_html else generated_html) + "</div>",
            "html.parser"
        )
        first_tag = findFirstTag(html_tree)

    # store original text as data-attribute on tree root
    encoded_field_html = base64.b64encode(field_html.encode('utf-8')).decode()
    first_tag['data-original-markdown'] = encoded_field_html

    return str(html_tree)


def findFirstTag(tree):
    """Find the first Tag element in an HTML tree."""
    for c in tree.children:
        if type(c) is Tag:
            return c
    return None


def getOriginalTextFromGenerated(field_html):
    """Extract the original markdown text from a generated HTML field."""
    first_tag = findFirstTag(BeautifulSoup(field_html, 'html.parser'))
    if first_tag is None or 'data-original-markdown' not in first_tag.attrs:
        return field_html

    encoded_bytes = first_tag['data-original-markdown'].encode()
    return base64.b64decode(encoded_bytes).decode('utf-8')


def fieldIsGeneratedHtml(field_html):
    """Check if a field's HTML was generated by this add-on."""
    if field_html is None:
        return False

    tree = BeautifulSoup(field_html, 'html.parser')
    first_tag = findFirstTag(tree)

    return (first_tag is not None
            and first_tag.attrs is not None
            and 'data-original-markdown' in first_tag.attrs)


def _get_note_type(note):
    """Get the note type dict, compatible with both old and new Anki API."""
    if hasattr(note, 'note_type'):
        return note.note_type()
    # Fallback for older Anki versions that still have model()
    return note.model()


def _get_field_dict(note, field_idx):
    """Get the field definition dict for a given field index."""
    note_type = _get_note_type(note)
    if note_type and 'flds' in note_type and field_idx < len(note_type['flds']):
        return note_type['flds'][field_idx]
    return None


def _is_auto_markdown_field(note, field_idx):
    """Check if a field is marked for auto-markdown conversion."""
    field = _get_field_dict(note, field_idx)
    if field is None:
        return False
    return field.get('perform-auto-markdown', False)


def _refresh_editor(editor):
    """Refresh the editor UI to reflect note field changes.
    
    Uses the modern API: loadNoteKeepingFocus() if available,
    otherwise falls back to loadNote().
    """
    if editor is None:
        return
    try:
        if hasattr(editor, 'loadNoteKeepingFocus'):
            editor.loadNoteKeepingFocus()
        elif hasattr(editor, 'loadNote'):
            editor.loadNote()
    except Exception:
        pass


def onMarkdownToggle(editor):
    """Toggle markdown conversion on the current field.
    
    If the field contains generated HTML → restore original markdown.
    If the field contains plain text → convert to markdown HTML.
    """
    if editor is None or editor.note is None:
        return

    field_id = editor.currentField
    if field_id is None:
        return

    note = editor.note

    if field_id >= len(note.fields):
        return

    field_html = note.fields[field_id]

    if fieldIsGeneratedHtml(field_html):
        # Convert back to plaintext markdown
        updated_html = getOriginalTextFromGenerated(field_html)
    else:
        # Convert plain text to markdown HTML
        # Strip HTML tags to get plain text for markdown processing
        plain_text = BeautifulSoup(field_html, 'html.parser').get_text()
        updated_html = generateHtmlFromMarkdown(plain_text, field_html)

    note.fields[field_id] = updated_html
    _refresh_editor(editor)


class EditorController(object):

    def __init__(self):
        self.editor = None

    # ── Hook callbacks (new gui_hooks signatures) ──

    def onEditorDidLoadNote(self, editor):
        """Called when the editor loads a note. Save the editor reference."""
        self.editor = editor

    def onEditorDidInitButtons(self, buttons, editor):
        """Called when editor buttons are being initialized.
        
        Always save editor reference. Optionally add the markdown toggle button.
        """
        self.editor = editor

    def setupEditorButtonsFilter(self, buttons, editor):
        """Add the markdown toggle button to the editor toolbar."""
        self.editor = editor

        key = QKeySequence(config.getManualMarkdownShortcut())
        try:
            # Qt6
            keyStr = key.toString(QKeySequence.SequenceFormat.NativeText)
        except AttributeError:
            # Qt5
            keyStr = key.toString(QKeySequence.NativeText)

        b = editor.addButton(
            os.path.join(addon_path, "icons", "markdown.png"),
            "markdown_button",
            onMarkdownToggle,
            keys=config.getManualMarkdownShortcut(),
            tip="Convert to/from Markdown ({})".format(keyStr)
        )

        buttons.append(b)
        return buttons

    def editFocusGainedHook(self, note, field_idx):
        """Called when a field gains focus. Restore markdown text if auto-enabled.
        
        New signature: (note: Note, current_field_idx: int)
        Note: editor is NOT passed — use self.editor saved from loadNote.
        """
        if not self.editor or not note:
            return

        if field_idx >= len(note.fields):
            return

        field_html = note.fields[field_idx]
        if not field_html:
            return

        is_auto = _is_auto_markdown_field(note, field_idx)
        is_generated = fieldIsGeneratedHtml(field_html)

        # If auto-markdown is enabled and field has generated HTML, restore markdown
        if config.isAutoMarkdownEnabled() and is_auto and is_generated:
            md = getOriginalTextFromGenerated(field_html)
            note.fields[field_idx] = md
            _refresh_editor(self.editor)

    def editFocusLostFilter(self, changed, note, field_idx):
        """Called when a field loses focus. Convert markdown to HTML if auto-enabled.
        
        New signature: (changed: bool, note: Note, current_field_idx: int) -> bool
        This is a FILTER — must return the 'changed' bool.
        """
        if not self.editor or not note:
            return changed

        if field_idx >= len(note.fields):
            return changed

        field_html = note.fields[field_idx]
        if not field_html:
            return changed

        is_auto = _is_auto_markdown_field(note, field_idx)
        is_generated = fieldIsGeneratedHtml(field_html)

        if config.isAutoMarkdownEnabled() and is_auto and not is_generated:
            # Get plain text from field and convert to markdown HTML
            plain_text = BeautifulSoup(field_html, 'html.parser').get_text()
            updated_html = generateHtmlFromMarkdown(plain_text, field_html)
            note.fields[field_idx] = updated_html
            _refresh_editor(self.editor)
            return True  # signal that the note was changed

        return changed
